### ISSUE TITLE
Issue in code results in vulnerability not found when exists.  

### ISSUE THREAD

**Issue by ChrisLPJones** [Hackmanit/TInjA#10]
I initially had a issue running TInjA against a know vulnerable service on Hack The Box.
after studying the verbose output and request.go code i noticed that the curl command being issued was incorrect.

Curl command: curl -X 'POST' -d 'invoice_id=?form_type=scannable_invoice?qr_link=%7B%23%23%7D%2F%2A%7B%7B.%7D%7D%2A%2F' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Cookie: session=eyJyb2xlIjoiMjEyMzJmMjk3YTU3YTVhNzQzODk0YTBlNGE4MDFmYzMifQ.Zi65ig.6k5or-nCIDegxaTlBXzXvD4eCwU' -H 'User-Agent: TInjA v1.1.3' 'http://capiclean.htb/QRGenerator'

the --data parameter had changed from the launching command and was being separated by "?" instead of "&" 

after changing 
https://github.com/Hackmanit/TInjA/blob/4e68e81d9a648482adb7abd0669d1db57888f43b/pkg/request.go#L125
https://github.com/Hackmanit/TInjA/blob/4e68e81d9a648482adb7abd0669d1db57888f43b/pkg/request.go#L128

i was able to get TInjA to successfully find the vulnerability.

i also noticed that when i moved the vulnerable --data position "qr_link" to the front of the  --data line that the payload way being inserted but wasn't ended with "&"
resulting in a failed attempt to find the vulnerability

Curl command: curl -X 'POST' -d 'qr_link=%5C%3C%5C%25%5C%27%5C%24%5C%7B%5C%7B%5C%2F%5C%23%5C%7B%5C%40%5C%7D%5C%7D%5C%25%5C%3E%5C%7B%5C%7Binvoice_id=&form_type=scannable_invoice' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Cookie: session=eyJyb2xlIjoiMjEyMzJmMjk3YTU3YTVhNzQzODk0YTBlNGE4MDFmYzMifQ.Zi65ig.6k5or-nCIDegxaTlBXzXvD4eCwU' -H 'User-Agent: TInjA v1.1.3' 'http://capiclean.htb/QRGenerator'

**Comment by m10x** [comment]
Oh dear, great catch! Thanks for the elaborated explanation and your effort to fix this slip-up. I'm going to check your PR soonish.

**Comment by m10x** [comment]
New version with your fix is released, thanks! https://github.com/Hackmanit/TInjA/releases/tag/1.1.4
