### ISSUE TITLE
go.mod:5: unknown directive: toolchain

### ISSUE THREAD

**Issue by nishantnishu29** [Hackmanit/TInjA#5]
go install -v github.com/Hackmanit/TInjA@latest
go: github.com/Hackmanit/TInjA@latest (in github.com/Hackmanit/TInjA@v0.0.0-20231212070943-de0be867841c): go.mod:5: unknown directive: toolchain
 get this error while installing Tinja

**Comment by m10x** [comment]
What go version are you using? You may need to use go 1.21.5 or higher. Otherwise you can use one of the precompiled binaries.

**Comment by nishantnishu29** [comment]
i am using go version go1.20.1
thanks

**Comment by m10x** [comment]
Then this will be the problem. Please update golang to the latest version or use one of the precompiled binaries. If a precompiled binary is missing for a specific architecture, feel free to open a new issue and we will compile it.
