### ISSUE TITLE
noAdditionalHeaders missing option

### ISSUE THREAD

**Issue by savushkin-yauheni** [Hackmanit/TInjA#8]
Hi guys!

I noticed  that you introduced `noAdditionalHeaders` option to skip headers checks. But it is not used anywhere. Could you please check it? 

regards

**Comment by m10x** [comment]
Hello @savushkin-yauheni you are right! I'll implement this feature soon :) 
Until it is released, I will keep this issue open.

**Comment by m10x** [comment]
The new release is available: https://github.com/Hackmanit/TInjA/releases/tag/1.1.2
